default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: hotellbestillingssystem_development
test:
  <<: *default
  database: hotellbestillingssystem_test
production:
  primary: &primary_production
    <<: *default
    database: hotellbestillingssystem_production
    username: hotellbestillingssystem
    password: <%= ENV["HOTELLBESTILLINGSSYSTEM_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: hotellbestillingssystem_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: hotellbestillingssystem_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: hotellbestillingssystem_production_cable
    migrations_paths: db/cable_migrate
